
###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "badong2001",
    "password": "124616",
    "email": "nguyenbadong01@gmail.com",
    "confirmPassword": "124616"
}

//token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDllMTUxYWU3OGE2OTFjODg0NTAyZjQiLCJyb2xlIjoidXNlciIsImlhdCI6MTYyMDk3MjgyNn0.Gusr1g03s5CYWDsOeCiIEOrtGUmNCfkoAB4u6Eos8pc

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "badong2001",
    "password": "124616"
}

###

GET http://localhost:5000/api/auth
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGEyM2ZjOWVmNmI3NTMxZWMyMTI4Y2MiLCJyb2xlIjoidXNlciIsImlhdCI6MTYyMTI0NTkzMH0.ZYckoIkn8C9tzJZ0XX5yjJcxU2vzUOFNPbLINvVDl6E

###

PATCH http://localhost:5000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGEyM2ZjOWVmNmI3NTMxZWMyMTI4Y2MiLCJyb2xlIjoidXNlciIsImlhdCI6MTYyMTI0NTkzMH0.ZYckoIkn8C9tzJZ0XX5yjJcxU2vzUOFNPbLINvVDl6E
Content-Type: application/json

{
    "fullname": "Nguyễn Bá Đông",
    "phoneNumber": "0834708721",
    "address": "Hà Nam",
    "accountBalance": 1000000
}

###

PATCH http://localhost:5000/api/auth/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGEyM2ZjOWVmNmI3NTMxZWMyMTI4Y2MiLCJyb2xlIjoidXNlciIsImlhdCI6MTYyMTI0NTkzMH0.ZYckoIkn8C9tzJZ0XX5yjJcxU2vzUOFNPbLINvVDl6E
Content-Type: application/json

{
    "password": "124616",
    "newPassword": "124616",
    "confirmPassword": "124616"
}