
###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "badong2000",
    "email": "nguyenbadong201@gmail.com",
    "password": "124616",
    "confirmPassword": "124616"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "badong2000",
    "password": "123456"
}

###

GET http://localhost:5000/api/auth
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGE2ODI3NTM4NTc4NTFmNDA1MThkMDAiLCJyb2xlIjoidXNlciIsImlhdCI6MTYyMTUyNTEwOSwiZXhwIjoxNjIxNTI1MTY5fQ.PUFAni-tPx8hGB2Y7IQUtpW6wsFgoE9jLZrTvdyhqyU

###

PATCH http://localhost:5000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGE2ODI3NTM4NTc4NTFmNDA1MThkMDAiLCJyb2xlIjoidXNlciIsImlhdCI6MTYyMTUyNTEwOSwiZXhwIjoxNjIxNTI1MTY5fQ.PUFAni-tPx8hGB2Y7IQUtpW6wsFgoE9jLZrTvdyhqyU
Content-Type: application/json

{
    "fullname": "Nguyễn Bá Đông",
    "phoneNumber": "0834708721",
    "address": "Hà Nam",
    "accountBalance": 1000000
}

###

PATCH http://localhost:5000/api/auth/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGE2ODI3NTM4NTc4NTFmNDA1MThkMDAiLCJyb2xlIjoidXNlciIsImlhdCI6MTYyMTUyNTE5NywiZXhwIjoxNjIxNTI1MjU3fQ.TsrZKaJ29Em4gW6vy3L5-cNs6tfE6mMu_IerbsOhHs0
Content-Type: application/json

{
    "password": "124616",
    "newPassword": "123456",
    "confirmPassword": "123456"
}

###

POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGE2ODI3NTM4NTc4NTFmNDA1MThkMDAiLCJpYXQiOjE2MjE1MjUyODMsImV4cCI6MTYyNDExNzI4M30.0NdWI2-C1dgdnHQfdWal81eSmyLKtYJ8qur4ugiCam8"
}

###

GET http://localhost:5000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGE2ODI3NTM4NTc4NTFmNDA1MThkMDAiLCJyb2xlIjoidXNlciIsImlhdCI6MTYyMTUyNTM1OSwiZXhwIjoxNjIxNTI1NDE5fQ.2wHeqrPra7MMxquH_bkWH9feWCE75I8O3_BnO8o2I9I
